version: "2"
services:
  pdns:
    #build: . 
    #image: secns/pdns
    image: pdns
    ports:
    - "53:53"
    - "53:53/udp"
    - "8080:80"
    - "8081:8081" #webserver + api rest port
    environment:
    - PDNS_ALLOW_AXFR_IPS=allow-axfr-ips=222.222.222.222\/32
    - PDNS_ALLOW_RECURSION=0.0.0.0\/0
    - PDNS_MASTER=yes
    - PDNS_SLAVE=no
    - PDNS_WEBSERVER_PASSWORD=test01
    - PDNS_API_KEY=secretkey01
    - PDNS_DISTRIBUTOR_THREADS=3
    - PDNS_CACHE_TTL=20
    - PDNS_RECURSIVE_CACHE_TTL=10
    - MYSQL_HOST=pdns_db
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
    labels:
      - "constraint:node==out.ba.infra-1" 

  pdns_db:
    image: mysql
    volumes:
    - pdns_mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
    labels:
      - "constraint:node==out.ba.infra-1" 


  pdns_slave:
    image: pdns
    ports:
    - "53:53"
    - "53:53/udp"
    - "8080:80"
    - "8081:8081" #webserver + api rest port
    environment:
    - PDNS_ALLOW_AXFR_IPS=127.0.0.1\/32
    - PDNS_ALLOW_RECURSION=0.0.0.0\/0
    - PDNS_MASTER=no
    - PDNS_SLAVE=yes
    - PDNS_MASTER_IP=1.1.1.1            # master name server IP
    - PDNS_SLAVE_FQDN=ns2.cloud.out.ba  # slave name server FQDN
    - PDNS_WEBSERVER_PASSWORD=test01
    - PDNS_API_KEY=secretkey01
    - PDNS_DISTRIBUTOR_THREADS=3
    - PDNS_CACHE_TTL=20
    - PDNS_RECURSIVE_CACHE_TTL=10
    - MYSQL_HOST=pdns_slave_db
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
     labels:
      - "constraint:node==out.ba.infra-2"

  pdns_slave_db:
    image: mysql
    volumes:
    - pdns_slave_mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
    labels:
      - "constraint:node==out.ba.infra-2"


volumes:
   pdns_mysql_data:
     driver: local
   pdns_slave_mysql_data:
     driver: local

